<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

	<bean id="patient" class="com.cma.spring.exceptiontest.Patient">
	<property name="emargencyContacts">
		<list>
			<ref bean="contact1" />
			<ref bean="contact2" />
			<ref bean="contact3" />
			<ref bean="contact4" />
		</list>
	</property>
	</bean>
	
	<bean id="contact1"
		class="com.cma.spring.exceptiontest.EmargencyContact">
	<property name="name" value="Abdullah"></property>
	<property name="phoneNumber" value="01717243358"></property>
	</bean>
	
	<bean id="contact2"
		class="com.cma.spring.exceptiontest.EmargencyContact">
	<property name="name" value="Abida"></property>
	<property name="phoneNumber" value="01717243359"></property>
	</bean>	
	
	<bean id="contact3"
		class="com.cma.spring.exceptiontest.EmargencyContact">
	<property name="name" value="Rafid"></property>
	<property name="phoneNumber" value="01717243367"></property>
	</bean>	
	
	<bean id="contact4"
		class="com.cma.spring.exceptiontest.EmargencyContact">
	<property name="name" value="Khalid"></property>
	<property name="phoneNumber" value="01717243387"></property>
	</bean>	
</beans>
